# Generated by Django 4.0.6 on 2022-07-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_table_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.CharField(blank='True', max_length=200, null=True),
        ),
    ]
